{{- if .Values.global.ingress.enabled -}}
{{- $hostDNS := .Values.global.ingress.host -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "helm-test.name" . }}-IngressRoute
spec:
  entryPoints:
    - web
  routes:
    {{- range .Values.global.ingress.paths }}
    - kind: Rule
      match: Host(`{{ $hostDNS }}`) && PathPrefix(`{{ .path }}`)
      middlewares:
        - name: gzip-compress
        - name: buffering-requests
        {{- if eq (trimPrefix "/" .path) "service-a" }}
        - name: strip-prefix-{{ trimPrefix "/" .path }}
        {{- end }}
        {{- if ne .path "/" }}
        - name: path-regex-{{ trimPrefix "/" .path }}
        {{- end }}
      services:
        - kind: Service
          {{ if eq .path "/" }}
          passHostHeader: true
          {{ end }}
          name: {{ default "service-a" (trimPrefix "/" .path) }}
          port: 80
    {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: gzip-compress
spec:
  compress: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: buffering-requests
spec:
  buffering:
    maxRequestBodyBytes: 104857600
{{- end }}
