# Global values for helm, overriden in each services values.yaml.

# Global values for helm, overriden in each services values.yaml.

global:

  imagePullSecrets:
    - name: "gcr-json-key"

  ingress:
    enabled: true
    annotations:
      # cert-manager.io/cluster-issuer: cluster-issuer
      # cert-manager.io/duration: "2160h"
      # cert-manager.io/renew-before: "360h"
      # external-dns.alpha.kubernetes.io/hostname: host.example.com
      # traefik.ingress.kubernetes.io/router.tls: "true"
      kubernetes.io/ingress.allow-http: "false"
      kubernetes.io/ingress.class: "traefik"
    host: super.devops.mikejoseph.com
    paths:
      - path: /
      - path: /service-a
      - path: /service-b
      - path: /service-c

  tolerations: []

  nodeSelector: {}

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: team
            operator: In
            values:
            - engineers

  data:
    KEY: VALUE
    # ...

